# Generated by Django 5.1 on 2024-08-29 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracker", "0002_rename_timeentry_timelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="createdDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
