# Generated by Django 5.1 on 2024-08-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetracker", "0003_timelog_createddate"),
    ]

    operations = [
        migrations.RemoveField(model_name="timelog", name="timeEnd",),
        migrations.RemoveField(model_name="timelog", name="timeStart",),
    ]
